# TRY401: Remove redundant exception in logging.exception calls
id: fix-exception-logging-with-var
message: "Remove redundant exception reference from logging.exception"
severity: info
language: python
rule:
  pattern: $LOGGER.exception($MSG, $EXC)
fix: |
  $LOGGER.exception($MSG)
